### ISSUE TITLE
Ask confirmation before installing python packages

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#1]
The installation of python dependencies should be done by leveraging `slicer.util.pip_install` and `slicer.util.confirmOkCancelDisplay`.

Consider reviewing the following for examples:
* https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#install-a-python-package
* https://github.com/PerkLab/SlicerSandbox/blob/e163d61c5babc25f53badb87f64cf4d123243c36/ImportOCT/ImportOCT.py#L44-L55
* https://github.com/SlicerMorph/SlicerMorph/blob/03d69077f35acda4012f830898e82657bb29e2b8/ALPACA/ALPACA.py#L182-L202

**Comment by Zaferyildiz** [comment]
@jcfr Thank you for the recommendation! Your request has been implemented in the following commit:

https://github.com/mazurowski-lab/SlicerSegmentWithSAM/commit/a38e2c6747817bfba3046391ade610bb13b4104e
