### ISSUE TITLE
Improve UI related to "Mask type"

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#11]
The UI provides the user with ability to select a mask type between `Mask-1`, `Mask-2` and `Mask-3`.

What is the difference between these ? Why would the user select one vs the other ?

**Comment by Zaferyildiz** [comment]
An explanatory tooltip added for the mask selection dropdown. Thanks for the suggestion.

**Comment by jcfr** [comment]
For reference, see https://github.com/mazurowski-lab/SlicerSegmentWithSAM/commit/8cb9617d4012de0fe6b661039796871aefc830d0
