### ISSUE TITLE
Add "How to cite"  section 

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#12]
Consider adding "How to cite" (for example, see `SlicerMorph`[^1]) section to the README.

[^1]: https://github.com/SlicerMorph/SlicerMorph#how-to-cite

**Comment by Zaferyildiz** [comment]
We are working on a paper about our extension. How to cite section will be added soon. Thanks for the suggestion.

**Comment by jcfr** [comment]
Exciting that you are getting a publication finalized.

I still suggest to add such a section that would:
* indicate you are are working on a publication that users looking to cite the extension should check back with the @mazurowski-lab 
* reference the original SAM paper: https://arxiv.org/abs/2304.02643
