### ISSUE TITLE
SegmentWithSAM extension not found in slicer

### ISSUE THREAD

**Issue by tueboesen** [mazurowski-lab/SlicerSegmentWithSAM#14]
I am trying to install the SlicerSegmentWithSAM extension, but when I search for the extension "SegmentWithSAM" nothing pops up. Did the extension change name or do I need to do something else first to make sure the extension can be found?

I downloaded the latest stable version of Slicer 3D from here for Linux https://download.slicer.org/, which is 5.6.1
After unpacking slicer I then went to the install extension section and tried searching for the extension but it does not show up. 

I see that the extension is also not available on:
https://extensions.slicer.org/catalog/All/32438/linux?q=

**Comment by Zaferyildiz** [comment]
@tueboesen SegmentWithSAM is released both on stable and preview versions of 3D Slicer now. You can install it through Extension Manager of 3D Slicer.
