### ISSUE TITLE
GPU Not Detected

### ISSUE THREAD

**Issue by wjh1065** [mazurowski-lab/SlicerSegmentWithSAM#3]
Hello,

I've noticed that my GPU is not being detected, and it defaults to the CPU. Is this intended?
![image](https://github.com/mazurowski-lab/SlicerSegmentWithSAM/assets/67947808/05d25c00-ee06-42f2-b994-c2f092c0493c)

Additionally, the tutorial video doesn't capture the mouse cursor, making it harder to follow.
I believe your extension pack will be very beneficial for me.

Thank you!

**Comment by Zaferyildiz** [comment]
Hi @wjh1065, PyTorch installation have been updated with one of the recent commits. Could you try to install the extension again? We will also update the tutorial video as there are new changes in the installation process.
