### ISSUE TITLE
Suggested cleanup

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#4]
* Remove registration of invalid SampleData in `registerSampleData()`
* Remove not implemented `SegmentWithSAMTest` class and remove `Testing` folder[^1]
* Remove not implemented/irrelevant `SegmentWithSAMLogic.process()` and consider moving relevant logic methods into it.
* Revisit implementation of `combineMultipleMasks`[^2] to be vectorized and more efficient

[^1]: https://github.com/mazurowski-lab/SlicerSegmentWithSAM/tree/main/SegmentWithSAM/Testing
[^2]: https://github.com/mazurowski-lab/SlicerSegmentWithSAM/blob/978447a69e1ccba022a2143216e518c2b5ebd8bd/SegmentWithSAM/SegmentWithSAM.py#L485C9-L495

**Comment by Zaferyildiz** [comment]
Requested changes have been implemented @jcfr. Thank you for the suggestions.
