### ISSUE TITLE
Console message about SAM checkpoint is reported in the console

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#6]
After loading a sample data and selecting the module, the following message is reported:
```
You need to put SAM checkpoint in /path/to/SlicerSegmentWithSAM-build/lib/Slicer-5.5/qt-scripted-modules/Resources/UI/../../../sam_vit_h_4b8939.pth and restart 3D Slicer!
```

Based on the `Installation via GitHub Repository`[^1] instructions, we can read the following:

> You should also download the [following checkpoint](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth) of SAM into the repository directory (in the same directory as the readme file).

The user of the extension should not be required to download such file, an informative message should be reported indicating that the download of the file will proceed after clicking "OK".

If using different checkpoint files is sensible, the may be provided with an advanced section enabling the user to set a different file.

The documentation of the extension should also include a section description what were checkpoint file and why different one would be used.

[^1]: https://github.com/mazurowski-lab/SlicerSegmentWithSAM#installation-via-github-repository

**Comment by Zaferyildiz** [comment]
The SAM checkpoint started to be downloaded automatically with the last commit. We did not want to put other checkpoints since they are not able to produce accurate segmentation results for most of the cases. Thanks for the suggestion.
