### ISSUE TITLE
Improve installation of segment-anything 

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#7]
The installation of `segment-anything` currently requires the user to have "git" installed. 

To move forward, revisit how the package is installed by installing from a remote url[^1] (for example `pip install segment_anything@https://github.com/facebookresearch/segment-anything/archive/refs/heads/main.zip`

[^1]: https://pip.pypa.io/en/stable/cli/pip_install/

**Comment by Zaferyildiz** [comment]
Git requirement is removed for segment-anything installation. Thanks for the suggestion.
