### ISSUE TITLE
Improve user experience related to installation of PyTorch dependent extension

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#9]
If `PyTorch` extension is not installed, the following message was reported in the console (hidden by default), the user should (1) be informed using a visual mechanism (e.g a pop-up) or (2) the dependent extension could be automatically installed.

I suggest to explicitly list `PyTorch` as an extension dependency.

```
Traceback (most recent call last):
  File "/path/to/SlicerSegmentWithSAM-build/lib/Slicer-5.5/qt-scripted-modules/SegmentWithSAM.py", line 85, in __init__
    raise RuntimeError(
RuntimeError: This module requires PyTorch extension. Install it from the Extensions Manager.
```

**Comment by Zaferyildiz** [comment]
@jcfr PyTorch has already been listed as a dependency in .s4ext file. Is there any way to install an extension from Extension Manager of 3D Slicer on code side? (such as slicer.util.pip_install)

**Comment by jcfr** [comment]
The dependent extension `PyTorch` should also be listed here:

https://github.com/mazurowski-lab/SlicerSegmentWithSAM/blob/dd0f59c05710cf86e1940455c7f41395f0a8bab7/CMakeLists.txt#L13

This will ensure that the locally generated `.s4ext` that you are contributing to the extensions index also include the relevant dependencies.

**Comment by Zaferyildiz** [comment]
@jcfr PyTorch dependency is added to CMakeList file as well.
